language: php

install:
  - composer self-update
  - composer --version
  - composer require phpunit/phpunit:*
  - vendor/bin/phpunit --version
  - composer require phpunit/phpunit:3.7.*
  - vendor/bin/phpunit --version
  - composer update
  - vendor/bin/phpunit --version
