language: php

install:
  - composer self-update
  - composer --version
  - composer require --prefer-source phpunit/phpunit:*
  - vendor/bin/phpunit --version
  - composer require --prefer-source phpunit/phpunit:3.7.*
  - vendor/bin/phpunit --version
  - composer --prefer-source update
  - vendor/bin/phpunit --version

php:
  - 5.5
